### ISSUE TITLE
Multiline replace not working

### ISSUE THREAD

**Issue by luxzeitlos** [erickrdch/grunt-string-replace#17]
Hello

A multiline pattern with the /m modifier is not working.

Thanks.

**Comment by envision** [comment]
I can verify. I'm trying to replace multiple lines of <script src="..."></script> tags that are like. I tried all the 4 variation of using " or ' and with or without \ endofline escaping.

        <script src="1"></script>
        <script src="2"></script>
        <script src="3"></script>

**Comment by erickrdch** [comment]
@envision I need a clear example of how it is not working. I need at least to know: your string-replace configuration, the file content (or a partial content) of the pattern and the replacement.

**Comment by chfw** [comment]
or how could grunt-string-replace do multiple line replacment? for example, here is my challenge to use grunt-string-replace, but no example was in your documentation:

    do not replace me
    // custom:tag
    replace me here
    //
    do not replace me

**Comment by eruizdechavez** [comment]
@chfw that is a regular expression replacement
