### ISSUE TITLE
Can you provide more examples and information?

### ISSUE THREAD

**Issue by yujiangshui** [erickrdch/grunt-string-replace#28]
At first, thanks for your great job!

I feel confused when I setting the files directory with the examples, and I setting as follow:

	prod: {
		files: {
			'./production/html/': '*.html'
		},
		options: {
			replacements: [{
				pattern: '<link rel="stylesheet" href="../style.dev.css" >',
				replacement: '<link rel="stylesheet" href="../style.css" >'
			}]
		}
	}

there are no error display, but no file change. So I find the question at [stackoverflow](http://stackoverflow.com/questions/17493094/grunt-string-replace-replace-string-in-all-files-in-a-directory-and-its-subdire) and the answer witch selected help me to figure out this problem:

	files: {
		'./': 'production/html/*.html'
	}

But I don't know why. So I hope you can give more examples or informations for people to avoid error.

Thanks again!

**Comment by erickrdch** [comment]
This is related to how grunt handles the files. If you want to understand better how this works you can go to http://gruntjs.com/configuring-tasks#files

**Comment by yujiangshui** [comment]
@erickrdch OK, tks
