### ISSUE TITLE
string-replace replacing unmatched characters

### ISSUE THREAD

**Issue by iabw** [erickrdch/grunt-string-replace#29]
'string-replace' logged that it had 'created' all of the files in my specified directory, even though none of the files actually matched my replacement config.

In some of those files, this saving process over-wrote some characters in my files with some other character that's showing up in my text editor as �, despite my config for string-replace specifying a specific string to replace. The replaced characters included smart quotes and a copyright symbol. It is still showing up "correctly" in the browser, so maybe it's just different flavors of unicode or something? I'm not an expert on this topic.

Interestingly, svn revert isn't fixing this character difference, so whatever 'string-replace' did to the smart-quote, svn doesn't seem to know it's different for revert purposes, although it DOES know it's different for saying the file has been modified ( which it shouldn't have been in the first place ).

my config looked like this -

    "string-replace": {
			velocity: {
				files: [{
					expand: true,
					cwd: "templates/velocity/",
					src: ['**/*.vm'],
					dest: 'templates/velocity/'
				}],
				options: {
					replacements: [{
						pattern: "#set($template_version =",
						replacement: '"#set($templateVersion ="'
					}]
				}
			}
		}

I would think that, ideally, grunt-string-replace would not save a file that it didn't think it was performing a replacement in. I saw it trigger my grunt-watch on my templates/velocity folder, and it seems like it would also not interact properly with grunt-newer.

**Comment by iabw** [comment]
Ignore the svn part of this. I think that was me being silly with my grunt-watch being configured to re-run grunt-string-replace.

As for not saving all files automatically, which solves the problem I had - changing lines 62-65 of tasks/lib/string-replace.js from this

        content = grunt.file.read(src);
        content = exports.multi_str_replace(content, replacements);
        grunt.file.write(dest, content);
        grunt.log.writeln('File ' + chalk.cyan(dest) + ' created.');

to this

        content = grunt.file.read(src);
        var newContent = exports.multi_str_replace(content, replacements);
        if (content != newContent){
            grunt.file.write(dest, newContent);
            grunt.log.writeln('File ' + chalk.cyan(dest) + ' created.');
        }

seems to work, and runs twice as fast, since in my case the number of files actually having a replace performed is far lower than the number being checked.

Is there a reason you would want all checked files saved that I'm missing?

**Comment by erickrdch** [comment]
I like the idea of not having to write a file without replacements, although technically this is a task of a copy or a glob to avoid running replacements on unnecessary files.

**Comment by erickrdch** [comment]
Implemented on v1.1.0

**Comment by erickrdch** [comment]
Changed on v1.2.0. Default behavior will NOT follow this approach. You can instruct `grunt-string-replace` to not copy unchanged files by setting `saveUnchanged` to `false`.

```
"string-replace": {
    foo: {
        files: [...],
        options: {
            saveUnchanged: false,
            replacements: [...]
        }
    }
}
```

**Comment by iabw** [comment]
Sounds good. Thank you for adding this.
