### ISSUE TITLE
Need to replace multiple instances of a pattern.

### ISSUE THREAD

**Issue by ankeetasingh** [erickrdch/grunt-string-replace#34]
Hello @erickrdch! 

I have a multiple instances (5) of a pattern in a file (app.yaml). When I run the grunt command, it only replaces the first instance of that pattern. Is there anything I am missing in the code?

Here's the code I have.
```
'string-replace' : {
            dist: {
                options: {
                    replacements: [
                        {
                            pattern: '@appName',
                            replacement: 'helloWorld'
                        }
                    ]
                },
                files: [
                    {
                        expand: true,
                        src: [
                          'app.yaml'
                        ]
                    }
                ]
            }
        }
```

**Comment by erickrdch** [comment]
Hi @ankeetasingh !

You are using a string as your replacement pattern. This plugin is a wrapper to [String.prototype.replace](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) which, in this case, will replace only the first occurrence. If you need to replace multiple times you should then use a regular expression. Try replacing `pattern: '@appName'` with `pattern: /@appName/g`.

**Comment by ankeetasingh** [comment]
Thank you @erickrdch !!
