### ISSUE TITLE
New dependencies in PATCH v1.3.2+ caused a break in v6.2.0 of Node

### ISSUE THREAD

**Issue by srogers909** [erickrdch/grunt-string-replace#52]
I understand that the new dependency upgrades in 1.3.2+ have pushed out the support for Node v6, etc.  

I have a project that is (unfortunately) stuck on v6.2.0 and we use this module.  We had our **package.json** set up with "grunt-string-replace": ^1.3.1 and the new update broke our build.  We resolved this by removing the carrot and staying at 1.3.1.  

We were expecting this module to conform to semantic versioning thus didn't expect a PATCH version update to cause a break in v6.2.0.  In my opinion, your change should have been a major version update in order to not break projects still on old Node versions.

**Comment by eruizdechavez** [comment]
I do agree with your comment, and I am sorry for creating that problem. I will keep this in mind if I have to do another dependency update to bump the version to 2.0.0 and unpublish 1.3.2.

That said, 1.3.1 would be only receiving code updates, not dependency updates as a) those are very old dependencies now, and b) Node 6 is no longer supported.
